// Generated by gencpp from file slugs_ros/SlugsTransExecutionArray.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONARRAY_H
#define SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONARRAY_H

#include <ros/service_traits.h>


#include <slugs_ros/SlugsTransExecutionArrayRequest.h>
#include <slugs_ros/SlugsTransExecutionArrayResponse.h>


namespace slugs_ros
{

struct SlugsTransExecutionArray
{

typedef SlugsTransExecutionArrayRequest Request;
typedef SlugsTransExecutionArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlugsTransExecutionArray
} // namespace slugs_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slugs_ros::SlugsTransExecutionArray > {
  static const char* value()
  {
    return "54bce38b27d158ed4216bcf42383f95d";
  }

  static const char* value(const ::slugs_ros::SlugsTransExecutionArray&) { return value(); }
};

template<>
struct DataType< ::slugs_ros::SlugsTransExecutionArray > {
  static const char* value()
  {
    return "slugs_ros/SlugsTransExecutionArray";
  }

  static const char* value(const ::slugs_ros::SlugsTransExecutionArray&) { return value(); }
};


// service_traits::MD5Sum< ::slugs_ros::SlugsTransExecutionArrayRequest> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsTransExecutionArray > 
template<>
struct MD5Sum< ::slugs_ros::SlugsTransExecutionArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsTransExecutionArray >::value();
  }
  static const char* value(const ::slugs_ros::SlugsTransExecutionArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsTransExecutionArrayRequest> should match 
// service_traits::DataType< ::slugs_ros::SlugsTransExecutionArray > 
template<>
struct DataType< ::slugs_ros::SlugsTransExecutionArrayRequest>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsTransExecutionArray >::value();
  }
  static const char* value(const ::slugs_ros::SlugsTransExecutionArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slugs_ros::SlugsTransExecutionArrayResponse> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsTransExecutionArray > 
template<>
struct MD5Sum< ::slugs_ros::SlugsTransExecutionArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsTransExecutionArray >::value();
  }
  static const char* value(const ::slugs_ros::SlugsTransExecutionArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsTransExecutionArrayResponse> should match 
// service_traits::DataType< ::slugs_ros::SlugsTransExecutionArray > 
template<>
struct DataType< ::slugs_ros::SlugsTransExecutionArrayResponse>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsTransExecutionArray >::value();
  }
  static const char* value(const ::slugs_ros::SlugsTransExecutionArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONARRAY_H
