// Generated by gencpp from file slugs_ros/SlugsGetInputsResponse.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSGETINPUTSRESPONSE_H
#define SLUGS_ROS_MESSAGE_SLUGSGETINPUTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slugs_ros
{
template <class ContainerAllocator>
struct SlugsGetInputsResponse_
{
  typedef SlugsGetInputsResponse_<ContainerAllocator> Type;

  SlugsGetInputsResponse_()
    : inputs_array()  {
    }
  SlugsGetInputsResponse_(const ContainerAllocator& _alloc)
    : inputs_array(_alloc)  {
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _inputs_array_type;
  _inputs_array_type inputs_array;




  typedef boost::shared_ptr< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SlugsGetInputsResponse_

typedef ::slugs_ros::SlugsGetInputsResponse_<std::allocator<void> > SlugsGetInputsResponse;

typedef boost::shared_ptr< ::slugs_ros::SlugsGetInputsResponse > SlugsGetInputsResponsePtr;
typedef boost::shared_ptr< ::slugs_ros::SlugsGetInputsResponse const> SlugsGetInputsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slugs_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'slugs_ros': ['/home/kchaudhari/catkin_ws/src/LTL_stack/slugs_ros/msg', '/home/kchaudhari/catkin_ws/devel/share/slugs_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a51f646ec2ead8a886f766b3088eba7";
  }

  static const char* value(const ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a51f646ec2ead8aULL;
  static const uint64_t static_value2 = 0x886f766b3088eba7ULL;
};

template<class ContainerAllocator>
struct DataType< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slugs_ros/SlugsGetInputsResponse";
  }

  static const char* value(const ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] inputs_array\n\
\n\
\n\
";
  }

  static const char* value(const ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inputs_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SlugsGetInputsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slugs_ros::SlugsGetInputsResponse_<ContainerAllocator>& v)
  {
    s << indent << "inputs_array[]" << std::endl;
    for (size_t i = 0; i < v.inputs_array.size(); ++i)
    {
      s << indent << "  inputs_array[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.inputs_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSGETINPUTSRESPONSE_H
