// Generated by gencpp from file slugs_ros/SlugsSetGoal.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSSETGOAL_H
#define SLUGS_ROS_MESSAGE_SLUGSSETGOAL_H

#include <ros/service_traits.h>


#include <slugs_ros/SlugsSetGoalRequest.h>
#include <slugs_ros/SlugsSetGoalResponse.h>


namespace slugs_ros
{

struct SlugsSetGoal
{

typedef SlugsSetGoalRequest Request;
typedef SlugsSetGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlugsSetGoal
} // namespace slugs_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slugs_ros::SlugsSetGoal > {
  static const char* value()
  {
    return "c81f0d6158d35853a2a0b98391969310";
  }

  static const char* value(const ::slugs_ros::SlugsSetGoal&) { return value(); }
};

template<>
struct DataType< ::slugs_ros::SlugsSetGoal > {
  static const char* value()
  {
    return "slugs_ros/SlugsSetGoal";
  }

  static const char* value(const ::slugs_ros::SlugsSetGoal&) { return value(); }
};


// service_traits::MD5Sum< ::slugs_ros::SlugsSetGoalRequest> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsSetGoal > 
template<>
struct MD5Sum< ::slugs_ros::SlugsSetGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsSetGoal >::value();
  }
  static const char* value(const ::slugs_ros::SlugsSetGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsSetGoalRequest> should match 
// service_traits::DataType< ::slugs_ros::SlugsSetGoal > 
template<>
struct DataType< ::slugs_ros::SlugsSetGoalRequest>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsSetGoal >::value();
  }
  static const char* value(const ::slugs_ros::SlugsSetGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slugs_ros::SlugsSetGoalResponse> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsSetGoal > 
template<>
struct MD5Sum< ::slugs_ros::SlugsSetGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsSetGoal >::value();
  }
  static const char* value(const ::slugs_ros::SlugsSetGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsSetGoalResponse> should match 
// service_traits::DataType< ::slugs_ros::SlugsSetGoal > 
template<>
struct DataType< ::slugs_ros::SlugsSetGoalResponse>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsSetGoal >::value();
  }
  static const char* value(const ::slugs_ros::SlugsSetGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSSETGOAL_H
