// Generated by gencpp from file slugs_ros/SlugsTransExecutionString.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONSTRING_H
#define SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONSTRING_H

#include <ros/service_traits.h>


#include <slugs_ros/SlugsTransExecutionStringRequest.h>
#include <slugs_ros/SlugsTransExecutionStringResponse.h>


namespace slugs_ros
{

struct SlugsTransExecutionString
{

typedef SlugsTransExecutionStringRequest Request;
typedef SlugsTransExecutionStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlugsTransExecutionString
} // namespace slugs_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slugs_ros::SlugsTransExecutionString > {
  static const char* value()
  {
    return "69c14fb59d97d9ff7647614172582a40";
  }

  static const char* value(const ::slugs_ros::SlugsTransExecutionString&) { return value(); }
};

template<>
struct DataType< ::slugs_ros::SlugsTransExecutionString > {
  static const char* value()
  {
    return "slugs_ros/SlugsTransExecutionString";
  }

  static const char* value(const ::slugs_ros::SlugsTransExecutionString&) { return value(); }
};


// service_traits::MD5Sum< ::slugs_ros::SlugsTransExecutionStringRequest> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsTransExecutionString > 
template<>
struct MD5Sum< ::slugs_ros::SlugsTransExecutionStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsTransExecutionString >::value();
  }
  static const char* value(const ::slugs_ros::SlugsTransExecutionStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsTransExecutionStringRequest> should match 
// service_traits::DataType< ::slugs_ros::SlugsTransExecutionString > 
template<>
struct DataType< ::slugs_ros::SlugsTransExecutionStringRequest>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsTransExecutionString >::value();
  }
  static const char* value(const ::slugs_ros::SlugsTransExecutionStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slugs_ros::SlugsTransExecutionStringResponse> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsTransExecutionString > 
template<>
struct MD5Sum< ::slugs_ros::SlugsTransExecutionStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsTransExecutionString >::value();
  }
  static const char* value(const ::slugs_ros::SlugsTransExecutionStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsTransExecutionStringResponse> should match 
// service_traits::DataType< ::slugs_ros::SlugsTransExecutionString > 
template<>
struct DataType< ::slugs_ros::SlugsTransExecutionStringResponse>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsTransExecutionString >::value();
  }
  static const char* value(const ::slugs_ros::SlugsTransExecutionStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONSTRING_H
