// Generated by gencpp from file slugs_ros/SlugsTransExecutionArrayRequest.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONARRAYREQUEST_H
#define SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONARRAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slugs_ros
{
template <class ContainerAllocator>
struct SlugsTransExecutionArrayRequest_
{
  typedef SlugsTransExecutionArrayRequest_<ContainerAllocator> Type;

  SlugsTransExecutionArrayRequest_()
    : trans_inputs_key_array()
    , trans_inputs_value_array()  {
    }
  SlugsTransExecutionArrayRequest_(const ContainerAllocator& _alloc)
    : trans_inputs_key_array(_alloc)
    , trans_inputs_value_array(_alloc)  {
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _trans_inputs_key_array_type;
  _trans_inputs_key_array_type trans_inputs_key_array;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _trans_inputs_value_array_type;
  _trans_inputs_value_array_type trans_inputs_value_array;




  typedef boost::shared_ptr< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SlugsTransExecutionArrayRequest_

typedef ::slugs_ros::SlugsTransExecutionArrayRequest_<std::allocator<void> > SlugsTransExecutionArrayRequest;

typedef boost::shared_ptr< ::slugs_ros::SlugsTransExecutionArrayRequest > SlugsTransExecutionArrayRequestPtr;
typedef boost::shared_ptr< ::slugs_ros::SlugsTransExecutionArrayRequest const> SlugsTransExecutionArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slugs_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'slugs_ros': ['/home/kchaudhari/catkin_ws/src/LTL_stack/slugs_ros/msg', '/home/kchaudhari/catkin_ws/devel/share/slugs_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81c070748689ff1ec13262fb9cfd7368";
  }

  static const char* value(const ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81c070748689ff1eULL;
  static const uint64_t static_value2 = 0xc13262fb9cfd7368ULL;
};

template<class ContainerAllocator>
struct DataType< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slugs_ros/SlugsTransExecutionArrayRequest";
  }

  static const char* value(const ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] trans_inputs_key_array\n\
bool[]   trans_inputs_value_array\n\
";
  }

  static const char* value(const ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trans_inputs_key_array);
      stream.next(m.trans_inputs_value_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SlugsTransExecutionArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slugs_ros::SlugsTransExecutionArrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "trans_inputs_key_array[]" << std::endl;
    for (size_t i = 0; i < v.trans_inputs_key_array.size(); ++i)
    {
      s << indent << "  trans_inputs_key_array[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.trans_inputs_key_array[i]);
    }
    s << indent << "trans_inputs_value_array[]" << std::endl;
    for (size_t i = 0; i < v.trans_inputs_value_array.size(); ++i)
    {
      s << indent << "  trans_inputs_value_array[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.trans_inputs_value_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSTRANSEXECUTIONARRAYREQUEST_H
