// Generated by gencpp from file slugs_ros/SlugsSetGoalRequest.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSSETGOALREQUEST_H
#define SLUGS_ROS_MESSAGE_SLUGSSETGOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slugs_ros
{
template <class ContainerAllocator>
struct SlugsSetGoalRequest_
{
  typedef SlugsSetGoalRequest_<ContainerAllocator> Type;

  SlugsSetGoalRequest_()
    : goal_id(0)  {
    }
  SlugsSetGoalRequest_(const ContainerAllocator& _alloc)
    : goal_id(0)  {
    }



   typedef int64_t _goal_id_type;
  _goal_id_type goal_id;




  typedef boost::shared_ptr< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SlugsSetGoalRequest_

typedef ::slugs_ros::SlugsSetGoalRequest_<std::allocator<void> > SlugsSetGoalRequest;

typedef boost::shared_ptr< ::slugs_ros::SlugsSetGoalRequest > SlugsSetGoalRequestPtr;
typedef boost::shared_ptr< ::slugs_ros::SlugsSetGoalRequest const> SlugsSetGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slugs_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'slugs_ros': ['/home/kchaudhari/catkin_ws/src/LTL_stack/slugs_ros/msg', '/home/kchaudhari/catkin_ws/devel/share/slugs_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88301c143434c2634c58261de7d34aaf";
  }

  static const char* value(const ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88301c143434c263ULL;
  static const uint64_t static_value2 = 0x4c58261de7d34aafULL;
};

template<class ContainerAllocator>
struct DataType< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slugs_ros/SlugsSetGoalRequest";
  }

  static const char* value(const ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 goal_id\n\
";
  }

  static const char* value(const ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SlugsSetGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slugs_ros::SlugsSetGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.goal_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSSETGOALREQUEST_H
