// Generated by gencpp from file slugs_ros/SlugsInitExecutionString.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONSTRING_H
#define SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONSTRING_H

#include <ros/service_traits.h>


#include <slugs_ros/SlugsInitExecutionStringRequest.h>
#include <slugs_ros/SlugsInitExecutionStringResponse.h>


namespace slugs_ros
{

struct SlugsInitExecutionString
{

typedef SlugsInitExecutionStringRequest Request;
typedef SlugsInitExecutionStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlugsInitExecutionString
} // namespace slugs_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slugs_ros::SlugsInitExecutionString > {
  static const char* value()
  {
    return "78d9b180a6363989c4867d53ceedde9f";
  }

  static const char* value(const ::slugs_ros::SlugsInitExecutionString&) { return value(); }
};

template<>
struct DataType< ::slugs_ros::SlugsInitExecutionString > {
  static const char* value()
  {
    return "slugs_ros/SlugsInitExecutionString";
  }

  static const char* value(const ::slugs_ros::SlugsInitExecutionString&) { return value(); }
};


// service_traits::MD5Sum< ::slugs_ros::SlugsInitExecutionStringRequest> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsInitExecutionString > 
template<>
struct MD5Sum< ::slugs_ros::SlugsInitExecutionStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsInitExecutionString >::value();
  }
  static const char* value(const ::slugs_ros::SlugsInitExecutionStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsInitExecutionStringRequest> should match 
// service_traits::DataType< ::slugs_ros::SlugsInitExecutionString > 
template<>
struct DataType< ::slugs_ros::SlugsInitExecutionStringRequest>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsInitExecutionString >::value();
  }
  static const char* value(const ::slugs_ros::SlugsInitExecutionStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slugs_ros::SlugsInitExecutionStringResponse> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsInitExecutionString > 
template<>
struct MD5Sum< ::slugs_ros::SlugsInitExecutionStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsInitExecutionString >::value();
  }
  static const char* value(const ::slugs_ros::SlugsInitExecutionStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsInitExecutionStringResponse> should match 
// service_traits::DataType< ::slugs_ros::SlugsInitExecutionString > 
template<>
struct DataType< ::slugs_ros::SlugsInitExecutionStringResponse>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsInitExecutionString >::value();
  }
  static const char* value(const ::slugs_ros::SlugsInitExecutionStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONSTRING_H
