// Generated by gencpp from file slugs_ros/SlugsInitExecutionStringResponse.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONSTRINGRESPONSE_H
#define SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONSTRINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slugs_ros
{
template <class ContainerAllocator>
struct SlugsInitExecutionStringResponse_
{
  typedef SlugsInitExecutionStringResponse_<ContainerAllocator> Type;

  SlugsInitExecutionStringResponse_()
    : current_inputs_outputs()  {
    }
  SlugsInitExecutionStringResponse_(const ContainerAllocator& _alloc)
    : current_inputs_outputs(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _current_inputs_outputs_type;
  _current_inputs_outputs_type current_inputs_outputs;




  typedef boost::shared_ptr< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SlugsInitExecutionStringResponse_

typedef ::slugs_ros::SlugsInitExecutionStringResponse_<std::allocator<void> > SlugsInitExecutionStringResponse;

typedef boost::shared_ptr< ::slugs_ros::SlugsInitExecutionStringResponse > SlugsInitExecutionStringResponsePtr;
typedef boost::shared_ptr< ::slugs_ros::SlugsInitExecutionStringResponse const> SlugsInitExecutionStringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace slugs_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'slugs_ros': ['/home/kchaudhari/catkin_ws/src/LTL_stack/slugs_ros/msg', '/home/kchaudhari/catkin_ws/devel/share/slugs_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbfd266a3c5b75f43d6a3ed5f4ee8bf4";
  }

  static const char* value(const ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbfd266a3c5b75f4ULL;
  static const uint64_t static_value2 = 0x3d6a3ed5f4ee8bf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slugs_ros/SlugsInitExecutionStringResponse";
  }

  static const char* value(const ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string current_inputs_outputs\n\
";
  }

  static const char* value(const ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_inputs_outputs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SlugsInitExecutionStringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slugs_ros::SlugsInitExecutionStringResponse_<ContainerAllocator>& v)
  {
    s << indent << "current_inputs_outputs: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.current_inputs_outputs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONSTRINGRESPONSE_H
