// Generated by gencpp from file slugs_ros/SlugsGetOutputs.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSGETOUTPUTS_H
#define SLUGS_ROS_MESSAGE_SLUGSGETOUTPUTS_H

#include <ros/service_traits.h>


#include <slugs_ros/SlugsGetOutputsRequest.h>
#include <slugs_ros/SlugsGetOutputsResponse.h>


namespace slugs_ros
{

struct SlugsGetOutputs
{

typedef SlugsGetOutputsRequest Request;
typedef SlugsGetOutputsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlugsGetOutputs
} // namespace slugs_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slugs_ros::SlugsGetOutputs > {
  static const char* value()
  {
    return "189a6272b7e6e367f3a14768143f8a56";
  }

  static const char* value(const ::slugs_ros::SlugsGetOutputs&) { return value(); }
};

template<>
struct DataType< ::slugs_ros::SlugsGetOutputs > {
  static const char* value()
  {
    return "slugs_ros/SlugsGetOutputs";
  }

  static const char* value(const ::slugs_ros::SlugsGetOutputs&) { return value(); }
};


// service_traits::MD5Sum< ::slugs_ros::SlugsGetOutputsRequest> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsGetOutputs > 
template<>
struct MD5Sum< ::slugs_ros::SlugsGetOutputsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsGetOutputs >::value();
  }
  static const char* value(const ::slugs_ros::SlugsGetOutputsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsGetOutputsRequest> should match 
// service_traits::DataType< ::slugs_ros::SlugsGetOutputs > 
template<>
struct DataType< ::slugs_ros::SlugsGetOutputsRequest>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsGetOutputs >::value();
  }
  static const char* value(const ::slugs_ros::SlugsGetOutputsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slugs_ros::SlugsGetOutputsResponse> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsGetOutputs > 
template<>
struct MD5Sum< ::slugs_ros::SlugsGetOutputsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsGetOutputs >::value();
  }
  static const char* value(const ::slugs_ros::SlugsGetOutputsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsGetOutputsResponse> should match 
// service_traits::DataType< ::slugs_ros::SlugsGetOutputs > 
template<>
struct DataType< ::slugs_ros::SlugsGetOutputsResponse>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsGetOutputs >::value();
  }
  static const char* value(const ::slugs_ros::SlugsGetOutputsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSGETOUTPUTS_H
