// Generated by gencpp from file slugs_ros/SlugsInitExecutionArray.msg
// DO NOT EDIT!


#ifndef SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONARRAY_H
#define SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONARRAY_H

#include <ros/service_traits.h>


#include <slugs_ros/SlugsInitExecutionArrayRequest.h>
#include <slugs_ros/SlugsInitExecutionArrayResponse.h>


namespace slugs_ros
{

struct SlugsInitExecutionArray
{

typedef SlugsInitExecutionArrayRequest Request;
typedef SlugsInitExecutionArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlugsInitExecutionArray
} // namespace slugs_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slugs_ros::SlugsInitExecutionArray > {
  static const char* value()
  {
    return "25d40750652088a9108edad12a666cca";
  }

  static const char* value(const ::slugs_ros::SlugsInitExecutionArray&) { return value(); }
};

template<>
struct DataType< ::slugs_ros::SlugsInitExecutionArray > {
  static const char* value()
  {
    return "slugs_ros/SlugsInitExecutionArray";
  }

  static const char* value(const ::slugs_ros::SlugsInitExecutionArray&) { return value(); }
};


// service_traits::MD5Sum< ::slugs_ros::SlugsInitExecutionArrayRequest> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsInitExecutionArray > 
template<>
struct MD5Sum< ::slugs_ros::SlugsInitExecutionArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsInitExecutionArray >::value();
  }
  static const char* value(const ::slugs_ros::SlugsInitExecutionArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsInitExecutionArrayRequest> should match 
// service_traits::DataType< ::slugs_ros::SlugsInitExecutionArray > 
template<>
struct DataType< ::slugs_ros::SlugsInitExecutionArrayRequest>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsInitExecutionArray >::value();
  }
  static const char* value(const ::slugs_ros::SlugsInitExecutionArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slugs_ros::SlugsInitExecutionArrayResponse> should match 
// service_traits::MD5Sum< ::slugs_ros::SlugsInitExecutionArray > 
template<>
struct MD5Sum< ::slugs_ros::SlugsInitExecutionArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slugs_ros::SlugsInitExecutionArray >::value();
  }
  static const char* value(const ::slugs_ros::SlugsInitExecutionArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slugs_ros::SlugsInitExecutionArrayResponse> should match 
// service_traits::DataType< ::slugs_ros::SlugsInitExecutionArray > 
template<>
struct DataType< ::slugs_ros::SlugsInitExecutionArrayResponse>
{
  static const char* value()
  {
    return DataType< ::slugs_ros::SlugsInitExecutionArray >::value();
  }
  static const char* value(const ::slugs_ros::SlugsInitExecutionArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLUGS_ROS_MESSAGE_SLUGSINITEXECUTIONARRAY_H
