(cl:defpackage slugs_ros-msg
  (:use )
  (:export
   "<STRINGARRAY>"
   "STRINGARRAY"
   "<SLUGSSYNTHESISACTIONFEEDBACK>"
   "SLUGSSYNTHESISACTIONFEEDBACK"
   "<SLUGSSYNTHESISGOAL>"
   "SLUGSSYNTHESISGOAL"
   "<SLUGSSYNTHESISACTION>"
   "SLUGSSYNTHESISACTION"
   "<SLUGSSYNTHESISFEEDBACK>"
   "SLUGSSYNTHESISFEEDBACK"
   "<SLUGSSYNTHESISACTIONRESULT>"
   "SLUGSSYNTHESISACTIONRESULT"
   "<SLUGSSYNTHESISRESULT>"
   "SLUGSSYNTHESISRESULT"
   "<SLUGSSYNTHESISACTIONGOAL>"
   "SLUGSSYNTHESISACTIONGOAL"
  ))

