set(_CATKIN_CURRENT_PACKAGE "hri_sphero_test")
set(hri_sphero_test_MAINTAINER "catherine <catherine@todo.todo>")
set(hri_sphero_test_DEPRECATED "")
set(hri_sphero_test_VERSION "0.0.0")
set(hri_sphero_test_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(hri_sphero_test_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(hri_sphero_test_BUILDTOOL_DEPENDS "catkin")