set(_CATKIN_CURRENT_PACKAGE "sphero_node")
set(sphero_node_MAINTAINER "Melonee Wise <melonee@meloneewise.com>")
set(sphero_node_DEPRECATED "")
set(sphero_node_VERSION "0.1.2")
set(sphero_node_BUILD_DEPENDS "geometry_msgs" "message_generation" "dynamic_reconfigure" "std_msgs")
set(sphero_node_RUN_DEPENDS "geometry_msgs" "message_runtime" "sphero_driver" "sphero_description" "dynamic_reconfigure" "sensor_msgs" "nav_msgs" "std_msgs" "tf" "python_orocos_kdl" "rospy")
set(sphero_node_BUILDTOOL_DEPENDS "catkin")