(cl:in-package slugs_ros-srv)
(cl:export '(TRANS_INPUTS_KEY_ARRAY-VAL
          TRANS_INPUTS_KEY_ARRAY
          TRANS_INPUTS_VALUE_ARRAY-VAL
          TRANS_INPUTS_VALUE_ARRAY
          CURRENT_INPUTS_OUTPUTS_KEY_ARRAY-VAL
          CURRENT_INPUTS_OUTPUTS_KEY_ARRAY
          CURRENT_INPUTS_OUTPUTS_VALUE_ARRAY-VAL
          CURRENT_INPUTS_OUTPUTS_VALUE_ARRAY
))