(cl:in-package slugs_ros-srv)
(cl:export '(INIT_INPUTS_OUTPUTS_KEY_ARRAY-VAL
          INIT_INPUTS_OUTPUTS_KEY_ARRAY
          INIT_INPUTS_OUTPUTS_VALUE_ARRAY-VAL
          INIT_INPUTS_OUTPUTS_VALUE_ARRAY
          CURRENT_INPUTS_OUTPUTS_KEY_ARRAY-VAL
          CURRENT_INPUTS_OUTPUTS_KEY_ARRAY
          CURRENT_INPUTS_OUTPUTS_VALUE_ARRAY-VAL
          CURRENT_INPUTS_OUTPUTS_VALUE_ARRAY
))