set(_CATKIN_CURRENT_PACKAGE "turns")
set(turns_MAINTAINER "kchaudhari <kchaudhari@todo.todo>")
set(turns_DEPRECATED "")
set(turns_VERSION "0.0.0")
set(turns_BUILD_DEPENDS "rospy")
set(turns_RUN_DEPENDS "rospy")
set(turns_BUILDTOOL_DEPENDS "catkin")